### ISSUE TITLE
Help with file structure

### ISSUE THREAD

**Issue by HillaryJuma** [nhs-r-community/Conference_2020#4]
Hey Chris, 

Thanks for submitting the pull request. 

I think I made the pull request incorrectly. The file is correct but it's not in plenary ttalks. 

Is it okay if you could move it please ?

Sorry

**Comment by ChrisBeeley** [comment]
Haha, I mindlessly clicked through them, my mistake :grin: 

Will do, thank you for the talk and the PR!
